name: Docker Image PHP-FPM
on:
  schedule:
    - cron: "0 6 * * *"   # 6 AM daily
  push:
    paths:
      - version
      - images/.trigger
      - images/php-fpm/**
      - .github/workflows/*php-fpm*
    branches:
      - main
jobs:
  php-fpm:
    name: FPM ${{ matrix.php_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version: [ "7.2", "7.3", "7.4", "8.0", "8.1" ]
    steps:
      - uses: actions/checkout@v1
      - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
        env:
          BUILD_GROUP: php-fpm
          PHP_VERSION: ${{ matrix.php_version }}
          PHP_VARIANT: ${{ matrix.php_variant }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_CRI_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CRI_USERNAME: ${{ github.repository_owner }}

  magento1:
    name: PHP-FPM ${{ matrix.php_version }} (magento1)
    runs-on: ubuntu-latest
    needs: php-fpm
    strategy:
      fail-fast: false
      matrix:
        php_version: [ "7.2", "7.3", "7.4", "8.0", "8.1" ]
    steps:
      - uses: actions/checkout@v1
      - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
        env:
          BUILD_GROUP: php-fpm/magento1
          PHP_VERSION: ${{ matrix.php_version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_CRI_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CRI_USERNAME: ${{ github.repository_owner }}

  magento2:
    name: PHP-FPM ${{ matrix.php_version }} (magento2)
    runs-on: ubuntu-latest
    needs: php-fpm
    strategy:
      fail-fast: false
      matrix:
        php_version: [ "7.2", "7.3", "7.4", "8.0", "8.1" ]
    steps:
      - uses: actions/checkout@v1
      - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
        env:
          BUILD_GROUP: php-fpm/magento2
          PHP_VERSION: ${{ matrix.php_version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_CRI_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CRI_USERNAME: ${{ github.repository_owner }}
